### ISSUE TITLE
veepooSDK_readSleepData

### ISSUE THREAD

**Issue by alxon** [HBandSDK/iOS_Ble_SDK#10]
I'm trying to get sleep data

1. For "VPPeripheralManage"

After calling "veepooSdkStartReadDeviceAllData", the "veepooSDKGetAccurateSleepData" function returns the correct data

2. For "VPPeripheralAddManage"

The "veepooSDK_readSleepData" function does not return data for the same day

What could be the reason? I checked in the demo project - the same thing - empty

I understand that this function (veepooSDK_readSleepData) is not described in the document, but I did not find any other functions for getting sleep data from the device

Thank you in advance

**Comment by helloveepoo** [comment]
Can not use "VPPeripheralManage" and "VPPeripheralAddManage" at the same time.

**Comment by alxon** [comment]
@helloveepoo 

These are different launches with different settings
Not at the same time

With "VPPeripheralAddManage" all other functions work:
"veepooSDK_readBasicData"
"veepooSDK_readDeviceAutoTestTemperatureData"
"veepooSDK_readStepData"

Only with "veepooSDK_readOxygenData" and "veepooSDK_readSleepData" nothing happens

How do I get sleep data in VPPeripheralAddManage mode?
