### ISSUE TITLE
[VPECGTestDataModel mj_keyValuesWithIgnoredKeys:]: unrecognized selector sent to instance 0x106e27820 2024-03-28 21:27:30.234869+0800 Runner[1872:773408] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[VPECGTestDataModel mj_keyValuesWithIgnoredKeys:]: unrecognized selector sent to instance 0x106e27820'

### ISSUE THREAD

**Issue by niuyannet** [HBandSDK/iOS_Ble_SDK#11]
获取基本数据：
VPBleCentralManage.sharedBleManager().peripheralManage.veepooSdkStartReadDeviceAllData
接口百分之百就报错了

**Comment by niuyannet** [comment]
滴滴

**Comment by helloveepoo** [comment]
这是一个很基本的错误，它不属于SDK的需要修复的。如果你阅读了doc中的使用指引文档或者demo，你不会遇到这种情况。
This is a very basic error that does not belong to the SDK and needs to be fixed. If you have read the usage instructions or demo in doc, you will not encounter this situation.
