### ISSUE TITLE
SW306 無法獲取 HRV 數據

### ISSUE THREAD

**Issue by MadmanChen0** [HBandSDK/iOS_Ble_SDK#13]
SW306 使用 H Band 有看到 HRV 的相關數據，
但是使用下面的方法取的數據都是空值，
`VPDataBaseOperation.veepooSDKGetDeviceHrvData(withDate: date, andTableID: address)`

已使用下面方法確認設備是支援 HRV
`VPBleCentralManage.sharedBleManager().peripheralManage.peripheralModel.hrvType != 0`

請問要如何解決無法讀取 HRV 的問題，謝謝!

**Comment by helloveepoo** [comment]
Sorry，HRV data is not free and requires commercial authorization.
