### ISSUE TITLE
In latest sdk version 2.9.10 after watch is connected in demo app, app is crashing  

### ISSUE THREAD

**Issue by elitechetan** [HBandSDK/iOS_Ble_SDK#3]
<img width="609" alt="Screenshot 2022-04-21 at 2 59 35 PM" src="https://user-images.githubusercontent.com/59273670/164426451-a84bb49e-1697-47cf-9b09-0a6953e2dd1c.png">

**Comment by bbigcd** [comment]
You can try this solution: https://stackoverflow.com/questions/3998483/objective-c-category-causing-unrecognized-selector/68708892#68708892

**Comment by MaNongWasi** [comment]
Adding `-ObjC` in Other Linker Flags option may help

**Comment by saytoonz** [comment]
1.  Select your Xcode project in the file navigator sidebar.      
2. Select your project in the sidebar and switch to the “Build Settings” tab.
3. Search for the `Other Linker Flags` setting.
4. Double click the `Other Linker Flags` row’s value area, on the right side. A pop-up should appear.
5. Add the `-ObjC` linker flag by pressing the “+” button
