### ISSUE TITLE
error Thread 1: "-[__NSCFString year]: unrecognized selector 

### ISSUE THREAD

**Issue by boottaa** [HBandSDK/iOS_Ble_SDK#4]
After call  veepooBleManager.peripheralManage.veepooSdkStartReadDeviceAllData{[weak self] 
Have error Thread 1: "-[__NSCFString year]: unrecognized selector sent to instance 0x2836ff300»  (@main)
if use @UIApplicationMain too have error
if use VPPeripheralManage.shareVPPeripheralManager()

if change to VPPeripheralAddManage.shareVPPeripheralManager() not have error bad cant read data (ReadDeviceAllData not working)

if change to 
How to fix it? How read data if use VPPeripheralAddManage or how fix "Have error Thread 1: "-[__NSCFString year]"?
Thank you very much for the answer!

**Comment by MaNongWasi** [comment]
Adding `-ObjC` in Other Linker Flags option may help

**Comment by saytoonz** [comment]
1.  Select your Xcode project in the file navigator sidebar.      
2. Select your project in the sidebar and switch to the “Build Settings” tab.
3. Search for the `Other Linker Flags` setting.
4. Double click the `Other Linker Flags` row’s value area, on the right side. A pop-up should appear.
5. Add the `-ObjC` linker flag by pressing the “+” button
