### ISSUE TITLE
导入VeepooBleSDK.framework一直报错是什么原因？

### ISSUE THREAD

**Issue by lgwResources** [HBandSDK/iOS_Ble_SDK#6]
Undefined symbols for architecture arm64:
  "_objc_msgSend$justCurrentSystemLanguageType", referenced from:
      +[NSString(Local) DPLocalizedString:comment:] in VeepooBleSDK(NSString+Local.o)
  "_objc_msgSend$initWithString:attributes:", referenced from:
      -[UILabel(Extension) changeWordSpace:] in VeepooBleSDK(UILabel+Extension.o)
      -[UILabel(Extension) changeLineSpace:WordSpace:] in VeepooBleSDK(UILabel+Extension.o)
  "_objc_msgSend$sizeToFit", referenced from:
      -[UILabel(Extension) changeLineSpace:] in VeepooBleSDK(UILabel+Extension.o)
      -[UILabel(Extension) changeWordSpace:] in VeepooBleSDK(UILabel+Extension.o)
      -[UILabel(Extension) changeLineSpace:WordSpace:] in VeepooBleSDK(UILabel+Extension.o)
  "_objc_msgSend$getRed:green:blue:alpha:", referenced from:
      +[UIColor(ChangeAlpha) getNewColorWith:alpha:] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$bloodMainCorlor", referenced from:
      +[UIColor(SleepColor) sleepAwakeCorlor] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$searchForColorByName:", referenced from:
      +[UIColor(UIColor_Expanded) colorWithName:] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$scanFloat:", referenced from:
      +[UIColor(UIColor_Expanded) colorWithString:] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$isAtEnd", referenced from:
      +[UIColor(UIColor_Expanded) colorWithString:] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$rgbHex", referenced from:
      -[UIColor(UIColor_Expanded) hexStringFromColor] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$alpha", referenced from:
      -[UIColor(UIColor_Expanded) stringFromColor] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$colorByAddingRed:green:blue:alpha:", referenced from:
      -[UIColor(UIColor_Expanded) colorByAddingColor:] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$colorByDarkeningToRed:green:blue:alpha:", referenced from:
      -[UIColor(UIColor_Expanded) colorByDarkeningTo:] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) colorByDarkeningToColor:] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$colorByLighteningToRed:green:blue:alpha:", referenced from:
      -[UIColor(UIColor_Expanded) colorByLighteningTo:] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) colorByLighteningToColor:] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$blue", referenced from:
      -[UIColor(UIColor_Expanded) rgbHex] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) stringFromColor] in VeepooBleSDK(UIColor+expanded.o)
  "_objc_msgSend$currentHandler", referenced from:
      -[UIColor(UIColor_Expanded) arrayFromRGBAComponents] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) red] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) green] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) blue] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) white] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) rgbHex] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) colorByLuminanceMapping] in VeepooBleSDK(UIColor+expanded.o)
      ...
  "_objc_msgSend$red:green:blue:alpha:", referenced from:
      -[UIColor(UIColor_Expanded) arrayFromRGBAComponents] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) rgbHex] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) colorByLuminanceMapping] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) colorByMultiplyingByRed:green:blue:alpha:] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) colorByAddingRed:green:blue:alpha:] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) colorByLighteningToRed:green:blue:alpha:] in VeepooBleSDK(UIColor+expanded.o)
      -[UIColor(UIColor_Expanded) colorByDarkeningToRed:green:blue:alpha:] in VeepooBleSDK(UIColor+expanded.o)
      ...
  "_objc_msgSend$numberWithFloat:", referenced from:
      -[UIColor(UIColor_Expanded) arrayFromRGBAComponents] in VeepooBleSDK(UIColor+expanded.o)
      -[UILabel(Extension) changeWordSpace:] in VeepooBleSDK(UILabel+Extension.o)
      -[UILabel(Extension) changeLineSpace:WordSpace:] in VeepooBleSDK(UILabel+Extension.o)
  "_objc_msgSend$errorWithDomain:code:userInfo:", referenced from:
      +[NSError(VPError) errorWithMessage:errorCode:] in VeepooBleSDK(NSError+VPError.o)
  "_objc_msgSend$zc_center", referenced from:
      -[UIView(Rect) setZc_centerX:] in VeepooBleSDK(UIView+Rect.o)
      -[UIView(Rect) setZc_centerY:] in VeepooBleSDK(UIView+Rect.o)
  "_objc_msgSend$setZc_top:", referenced from:
      -[UIView(Rect) setZc_center:] in VeepooBleSDK(UIView+Rect.o)
  "_objc_msgSend$zc_left", referenced from:
      -[UIView(Rect) zc_center] in VeepooBleSDK(UIView+Rect.o)
  "_objc_msgSend$zc_middleY", referenced from:
      -[UIView(Rect) zc_center] in VeepooBleSDK(UIView+Rect.o)
      -[UIView(Rect) setZc_center:] in VeepooBleSDK(UIView+Rect.o)
      -[UIView(Rect) zc_middlePoint] in VeepooBleSDK(UIView+Rect.o)
  "_objc_msgSend$setZc_x:", referenced from:
      -[UIView(Rect) setZc_left:] in VeepooBleSDK(UIView+Rect.o)
      -[UIView(Rect) setZc_right:] in VeepooBleSDK(UIView+Rect.o)
  "_objc_msgSend$oneDayOxygens", referenced from:
      -[VPOxygenAnalysisModel vp_parseOSAHSResultOtherResult] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$setAveRespirationRate:", referenced from:
      -[VPOxygenAnalysisModel vp_parseOSAHSResultOtherResult] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$setMinRespirationRate:", referenced from:
      -[VPOxygenAnalysisModel vp_parseOSAHSResultOtherResult] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$setMaxCardiacLoad:", referenced from:
      -[VPOxygenAnalysisModel vp_parseOSAHSResultOtherResult] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$frequentOccurrenceTimes", referenced from:
      -[VPOxygenAnalysisModel vp_parseOSAHSFrequentOccurrenceTime] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$setOsahsResult:", referenced from:
      -[VPOxygenAnalysisModel vp_parseOSAHSResult] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$setOsahsResultDes:", referenced from:
      -[VPOxygenAnalysisModel vp_parseOSAHSResult] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$setParseOneDayDict:", referenced from:
      -[VPOxygenAnalysisModel setOneDayOxygens:] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$vp_parseOSAHSResult", referenced from:
      -[VPOxygenAnalysisModel setOneDayOxygens:] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$vp_parseOSAHSFrequentOccurrenceTime", referenced from:
      -[VPOxygenAnalysisModel setOneDayOxygens:] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$setOneDayOxygens:", referenced from:
      -[VPOxygenAnalysisModel initWithOneDayOxygens:] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$durationTime", referenced from:
      -[VPOxygenApneaRemindModel copyWithZone:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
  "_objc_msgSend$defaultTime", referenced from:
      -[VPOxygenApneaRemindModel copyWithZone:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
  "_objc_msgSend$endH", referenced from:
      -[VPOxygenApneaRemindModel getSettingDataWithType:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel copyWithZone:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
  "_objc_msgSend$endM", referenced from:
      -[VPOxygenApneaRemindModel getSettingDataWithType:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel copyWithZone:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
  "_objc_msgSend$setDurationTime:", referenced from:
      -[VPOxygenApneaRemindModel initWithData:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel copyWithZone:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
  "_objc_msgSend$setStartH:", referenced from:
      -[VPOxygenApneaRemindModel init] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel initWithData:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel copyWithZone:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
  "_objc_msgSend$setStartM:", referenced from:
      -[VPOxygenApneaRemindModel init] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel initWithData:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel copyWithZone:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
  "_objc_msgSend$setEndH:", referenced from:
      -[VPOxygenApneaRemindModel init] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel initWithData:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel copyWithZone:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
  "_objc_msgSend$setEndM:", referenced from:
      -[VPOxygenApneaRemindModel init] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel initWithData:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
      -[VPOxygenApneaRemindModel copyWithZone:] in VeepooBleSDK(VPOxygenApneaRemindModel.o)
  "_objc_msgSend$handleOneDayTemperatureData:", referenced from:
      -[VPPeripheralManage peripheral:didUpdateValueForCharacteristic:error:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$handleOneDayAllFiveMinuteData:", referenced from:
      -[VPPeripheralManage peripheral:didUpdateValueForCharacteristic:error:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$setAveLowOxygenTime:", referenced from:
      -[VPOxygenAnalysisModel vp_parseOSAHSResultOtherResult] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$veepooSDKFindDifferenceCrcValueWithTbyte:", referenced from:
      -[VPPeripheralManage peripheral:didUpdateValueForCharacteristic:error:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$veepooSDKHandleRunningDataWithTbyte:", referenced from:
      -[VPPeripheralManage peripheral:didUpdateValueForCharacteristic:error:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$setAveSleepActivity:", referenced from:
      -[VPOxygenAnalysisModel vp_parseOSAHSResultOtherResult] in VeepooBleSDK(VPOxygenAnalysisModel.o)
  "_objc_msgSend$handleOneDayDailyData:", referenced from:
      -[VPPeripheralManage peripheral:didUpdateValueForCharacteristic:error:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$handleOneDayAllSleepData:", referenced from:
      -[VPPeripheralManage peripheral:didUpdateValueForCharacteristic:error:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$temperatureType", referenced from:
      -[VPPeripheralManage veepooSdkStartReadDeviceTemperatureData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$setVPReadDeviceOxygenDataBlock:", referenced from:
      -[VPPeripheralManage veepooSdkStartReadDeviceOxygenData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$lastReadTodayOxygenDataMaxPackage", referenced from:
      -[VPPeripheralManage veepooSdkStartReadDeviceOxygenData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$veepooSDKReadDeviceRunningData", referenced from:
      -[VPPeripheralManage veepooSDKFindDifferenceCrcValueWithTbyte:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSDKHandleRunningDataWithTbyte:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$veepooSDKReadDeviceRunningCrc", referenced from:
      -[VPPeripheralManage veepooSDKStartReadDeviceRunningData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$checkLastWeekTemperatrueDatabaseVerssion", referenced from:
      -[VPPeripheralManage readDeviceTemperatureDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$storeReadHrvMaxPackage:", referenced from:
      -[VPPeripheralManage readDeviceHRVDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$checkLastWeekHrvDatabaseVerssion", referenced from:
      -[VPPeripheralManage readDeviceHRVDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$checkLastWeekOxygenDatabaseVerssion", referenced from:
      -[VPPeripheralManage readDeviceOxygenDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$storeReadMaxPackage:", referenced from:
      -[VPPeripheralManage readDeviceAllDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$checkLastWeekDatabaseVerssion", referenced from:
      -[VPPeripheralManage readDeviceAllDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$lastReadTodayDataMaxPackage", referenced from:
      -[VPPeripheralManage readDeviceSleepDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$VPReadDeviceTemperatureDataBlock", referenced from:
      -[VPPeripheralManage handleOneDayTemperatureData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage readDeviceTemperatureDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSdkStartReadDeviceTemperatureData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$handleOneDayTemperatrueDataWithDayNumber:temperatrueData:isCorver:", referenced from:
      -[VPPeripheralManage handleOneDayTemperatureData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$readNextDayTemperatureDataWithDayNumber:deviceSaveTotalDays:tableID:", referenced from:
      -[VPPeripheralManage handleOneDayTemperatureData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$readDeviceTemperatureDataComplete", referenced from:
      -[VPPeripheralManage handleOneDayTemperatureData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$handleNewOneDayHRVDataWithDayNumber:hrvData:isCorver:", referenced from:
      -[VPPeripheralManage handleNewOneDayHRVData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$VPReadDeviceHrvDataBlock", referenced from:
      -[VPPeripheralManage handleOneDayHRVData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleNewOneDayHRVData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage readDeviceHRVDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSdkStartReadDeviceHrvData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$readOneDayHrvData", referenced from:
      -[VPPeripheralManage handleOneDayHRVData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleNewOneDayHRVData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSdkStartReadDeviceHrvData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$VPReadDeviceOxygenDataBlock", referenced from:
      -[VPPeripheralManage handleOneDayOxygenData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage readDeviceOxygenDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSdkStartReadDeviceOxygenData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$readDeviceOxygenDataComplete", referenced from:
      -[VPPeripheralManage handleOneDayOxygenData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$readOneDayOxygenData", referenced from:
      -[VPPeripheralManage handleOneDayOxygenData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSdkStartReadDeviceOxygenData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$sleepType", referenced from:
      -[VPPeripheralManage handleOneDayAllSleepData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$readDeviceSleepDataComplete", referenced from:
      -[VPPeripheralManage handleOneDayAllSleepData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$initWithDeviceMac:andStatus:hrvType:oxygenType:", referenced from:
      -[VPPeripheralManage handleOneDayDailyData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$handleOneDayDailyData:dayNumber:isCorver:protocolType:", referenced from:
      -[VPPeripheralManage handleOneDayDailyData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$handleOneDayFiveMinuteDataWithDayNumber:FiveMinuteData:userStature:corver:modifyProtocol:", referenced from:
      -[VPPeripheralManage handleOneDayAllFiveMinuteData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$readNextDayFiveDataWithDayNumber:deviceSaveTotalDays:tableID:", referenced from:
      -[VPPeripheralManage handleOneDayAllFiveMinuteData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleOneDayDailyData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$readDeviceFiveDataComplete", referenced from:
      -[VPPeripheralManage handleOneDayAllFiveMinuteData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleOneDayDailyData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$readOneDayFiveOriginalData", referenced from:
      -[VPPeripheralManage handleOneDayAllFiveMinuteData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleOneDayDailyData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage readDeviceSleepDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$handleOneTimesDrinkData:", referenced from:
      -[VPPeripheralManage handleOneTimesDrinkData:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$currentRunningTimes", referenced from:
      -[VPPeripheralManage veepooSDKReadDeviceRunningData] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSDKHandleRunningDataWithTbyte:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$VPReadDeviceRunningDataBlock", referenced from:
      -[VPPeripheralManage veepooSDKReadDeviceRunningCrc] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSDKReadDeviceRunningData] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSDKStartReadDeviceRunningData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage veepooSDKHandleRunningDataWithTbyte:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage peripheral:didUpdateValueForCharacteristic:error:] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$VPReadDeviceBaseDataBlock", referenced from:
      -[VPPeripheralManage veepooSdkStartReadDeviceAllDataWithReadStateChangeBlock:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleOneDayAllFiveMinuteData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleOneDayDailyData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage readDeviceAllDataComplete] in VeepooBleSDK(VPPeripheralManage.o)
  "_objc_msgSend$saveDays", referenced from:
      -[VPPeripheralManage veepooSdkStartReadDeviceAllDataWithReadStateChangeBlock:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleOneDayAllFiveMinuteData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleOneDayDailyData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleOneDayAllSleepData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleOneDayHRVData:] in VeepooBleSDK(VPPeripheralManage.o)
      -[VPPeripheralManage handleNewOneDayHRVData:] in VeepooBleSDK(VPPeripheralManage.o)

**Comment by helloveepoo** [comment]
使用说明.docx 中的11.Other Linker Flags下添加-ObjC

**Comment by lgwResources** [comment]
添加了也是报错，使用2.0.43.15版本不报错

**Comment by lgwResources** [comment]
能不能来个人解答一下，目前只能用2.0.43.15不报错，获取表盘市场也获取不到
Xcode 13.2.1   
Other Linker Flags中也设置了-ObjC

**Comment by EmmaMeng** [comment]
> 使用说明.docx 中的11.Other Linker Flags下添加-ObjC

请问使用说明在哪看呀？我看着wiki里的接口文档只写了接口的功能，集成步骤都没有，依赖库啥的配置在哪看呀

**Comment by lgwResources** [comment]
> 请问使用说明在哪看呀？我看着wiki里的接口文档只写了接口的功能，集成步骤都没有，依赖库啥的配置在哪看呀

<img width="870" alt="图片" src="https://github.com/HBandSDK/iOS_Ble_SDK/assets/25788353/6aa3e2fe-7d6d-4d9a-bf58-77ca66b7dfbd">
Demo下载下来后里面有文档
