### ISSUE TITLE
Not able to run the app after updating to latest sdk version

### ISSUE THREAD

**Issue by elitechetan** [HBandSDK/iOS_Ble_SDK#8]
<img width="410" alt="Screenshot 2024-01-17 at 3 21 41 PM" src="https://github.com/HBandSDK/iOS_Ble_SDK/assets/59273670/097c3953-1426-4265-99a1-3ae35c096774">

**Comment by geekswamp** [comment]
+1

**Comment by helloveepoo** [comment]
@elitechetan Are the Xcode versions the same before and after the SDK update?

**Comment by helloveepoo** [comment]
![image](https://github.com/HBandSDK/iOS_Ble_SDK/assets/40560874/b0855684-0364-4d50-9080-2ee92c2ad8f6)

**Comment by elitechetan** [comment]
Xcode is updated to latest .

**Comment by helloveepoo** [comment]
![image](https://github.com/HBandSDK/iOS_Ble_SDK/assets/40560874/70ea237d-45f6-4eb7-982a-caf7e712b727)
try adding -ld_classic

**Comment by geekswamp** [comment]
> ![image](https://private-user-images.githubusercontent.com/40560874/297725320-70ea237d-45f6-4eb7-982a-caf7e712b727.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODQ2NDIsIm5iZiI6MTcwNTU4NDM0MiwicGF0aCI6Ii80MDU2MDg3NC8yOTc3MjUzMjAtNzBlYTIzN2QtNDVmNi00ZWI3LTk4MmEtY2FmN2U3MTJiNzI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzMjU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNGE0NTU1ZTg5MDcwODE0MjJmM2UwMTRkZjE5Y2U5M2U3OWQ5OGM4NWM0YzY1NzIzYWE5NThkODFjZDI5MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pwc1Q-1Z-ipsvMjaEzsdstFjmO5aHTXaQMsWoa-sG08) try adding -ld_classic

Hi, i already added the `-Id_classic`, but i ge errors like this:
<img width="138" alt="Screenshot 2024-01-18 at 20 40 34" src="https://github.com/HBandSDK/iOS_Ble_SDK/assets/16235886/11b5d624-f6ca-436b-b536-3acce68fed6d">
<img width="275" alt="Screenshot 2024-01-18 at 20 40 41" src="https://github.com/HBandSDK/iOS_Ble_SDK/assets/16235886/c75f15f6-35e3-4bb1-979f-0a6b0cafca84">

**Comment by helloveepoo** [comment]
@arifai Hi, you can try to re-install your pods.
this error is Your Project can not link 'iOSDFULibrary'.
Similar errors usually occur after Xcode updates.
ref: https://github.com/facebook/react-native/issues/39378

**Comment by geekswamp** [comment]
> @arifai Hi, you can try to re-install your pods. this error is Your Project can not link 'iOSDFULibrary'. Similar errors usually occur after Xcode updates. ref: [facebook/react-native#39378](https://github.com/facebook/react-native/issues/39378)

It works, thank you.
