### ISSUE TITLE
App crash while connecting to h Band app and my App.

### ISSUE THREAD

**Issue by Allamprabhu1058** [HBandSDK/iOS_Ble_SDK#9]
Hi,

I have connected my wearable device to h band app and then trying to connect same wearable device in my app, then my app is crashed. If i connect only my app it is working fine.

* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x11)
    frame #0: 0x0000000104d8bb20 hband_wearable`-[VPDeviceAlarmDataHandle sdk_handleDeviceAlarmDataWithData:](self=0x00000002808251f0, _cmd="sdk_handleDeviceAlarmDataWithData:", data=20 bytes) at VPDeviceAlarmDataHandle.m:58:9
Target 0: (Runner) stopped.

**Comment by helloveepoo** [comment]
Do not allow two APPs to connect to the same device
